# 1. Introducción
En Python, cualquier tabla se puede representar como un arreglo de arreglos (un arreglo, donde cada elemento es a su vez un arreglo)

<center><img src="Figures/S4-DistanceTable.png" width="800" height="1100"></center>

In [ ]:
distances = [
[0,    983,  787, 714, 1375, 967, 1087],
[983,  0,    214, 1102, 1763, 1723, 1842],
[787,  214,  0, 888, 1549, 1548, 1627],
[714,  1102, 888, 0, 661, 781, 810],
[1375, 1763, 1549, 661, 0, 1426, 1187],
[967,  1723, 1548, 781, 1426, 0, 239],
[1087, 1842, 1627, 810, 1187, 239, 0],
]

print(distances)
print(distances[0])
print(distances[1])
print(distances[1][0])

## Declaración de arreglos de dos dimensiones
Veamos el siguiente ejemplo.

In [ ]:
edadesEmpresa = [[34,25,16,32],
                 [34,13,76,23]] # Arreglo simétrico
edadesEmpresa2 = [[34,25,16,32], 
                  [34,13,76]   ] # Arreglo asimétrico

### 1. Primera forma:
Puede crear una lista de n elementos (por ejemplo, de n ceros) y luego hacer que cada uno de los elementos sea un enlace a otra lista unidimensional de m elementos:

In [ ]:
f = 2
c = 3
a = [0] * f
for i in range(f):
    a[i] = [0] * c
print(a)

### 2. Segunda forma:
Otra forma (pero similar): crear una lista vacía y luego append un nuevo elemento n veces (este elemento debe ser una lista de longitud m ):

In [ ]:
f = 2
c = 3
a = []
for i  in range(f):
    x = [0] * c
    a.append(x)
print(a)

### 3. Tercera forma:
Pero la forma más fácil es usar generator, creando una lista de n elementos, cada uno de los cuales es una lista de m ceros:

In [ ]:
f = 6
c = 3
a = [[0]*c for i in range(f)]
print(a)

<center><img src="Figures/S4-FilasColumnas.png" width="500" height="800"></center>

# Utilizando los arreglos de dos dimensiones

## Métodos que se pueden usar con arreglos (o listas)

|Método||Descripción|
| --- || --- |
|append()||Agrega un elemento al final de la lista|
|clear()||Elimina todos los elementos de la lista|
|copy()||Devuelve una copia de la lista|
|count()||Devuelve el número de elementos con el valor especificado|
|extend()||Agrega los elementos de una lista (o cualquier iterable), al final de la lista actual|
|index()||Devuelve el índice del primer elemento con el valor especificado|
|insert()||Agrega un elemento en la posición especificada|
|pop()||Elimina el elemento en la posición especificada|
|remove()||Elimina el primer elemento con el valor especificado|
|reverse()||Invierte el orden de la lista|
|sort()||Ordena la lista|

### 1. Acceso a elementos de un arreglo
Para acceder a un elemento individual de un arreglo, basta con colocar el nombre de la variable, seguido por dos corchetes [][], y dentro de los corchetes colocar los indices del elemetos al que se quiere acceder.

<center><img src="Figures/S4-Asignacion.png" width="500" height="800"></center>

Veamos el siguiente ejemplo:

In [6]:
edadesEmpresa = [[34,25,16,32],[34,13,76,23]]
print(edadesEmpresa)
print(edadesEmpresa[0])
print(edadesEmpresa[0][1])
print(len(edadesEmpresa))
print(len(edadesEmpresa[0]))
print(len(edadesEmpresa[1]))

edadesEmpresa2 = [[34,25,16,32],[34,13,76]]
print(len(edadesEmpresa2))
print(len(edadesEmpresa2[0]))
print(len(edadesEmpresa2[1]))

[[34, 25, 16, 32], [34, 13, 76, 23]]
[34, 25, 16, 32]
25
2
4
4
2
4
3


In [7]:
edadesEmpresa2 = [[34,25,16,32],[34,13,76]]

#Recorriendo matriz por filas
for i in range(len(edadesEmpresa2)):
    for j in range(len(edadesEmpresa2[i])):
        print(f"Valor en la posición i={i}, j={j} ->{edadesEmpresa2[i][j]}")

Valor en la posición i=0, j=0 ->34
Valor en la posición i=0, j=1 ->25
Valor en la posición i=0, j=2 ->16
Valor en la posición i=0, j=3 ->32
Valor en la posición i=1, j=0 ->34
Valor en la posición i=1, j=1 ->13
Valor en la posición i=1, j=2 ->76


In [10]:
edadesEmpresa2 = [[34,25,16,32],[34,13,76]]

#Recorriendo matriz por columnas
for i in range(len(edadesEmpresa2[0])):
    for j in range(len(edadesEmpresa2)):
        try:
            print(f"Valor en la posición j={j}, i={i} ->{edadesEmpresa2[j][i]}")
        except IndexError: 
            print(f"Valor en la posición j={j}, i={i} -> Esta vacía")

Valor en la posición j=0, i=0 ->34
Valor en la posición j=1, i=0 ->34
Valor en la posición j=0, i=1 ->25
Valor en la posición j=1, i=1 ->13
Valor en la posición j=0, i=2 ->16
Valor en la posición j=1, i=2 ->76
Valor en la posición j=0, i=3 ->32
Valor en la posición j=1, i=3 -> Esta vacía


## 2. Modificar elementos de un arreglo de dos dimensiones
Para modificar datos de un arreglo basta con especificar la posición que se quiere modificar, y luego colocar un “=“, y finalmente el nuevo valor que se desea asignar.

In [11]:
f = 6
c = 3
a = [[0]*c for i in range(f)]
print(a)

a[2][1] = 7
print(a)

#¿Dónde coloca el valor?

[[0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0]]


<center><img src="Figures/S4-FilasColumnasValor.png" width="500" height="800"></center>

### Llenando una matriz con input

In [12]:
f = int(input("Cuántas empresas?"))
c = int(input("Cuántos empleados?"))
matriz = [[0] * c for i in range(f)]
print(matriz)

for i in range(f):
    for j in range(c):
        valor = int(input(f"Ingrese el valor para la empresa {i}, empleado{j}"))
        matriz[i][j] = valor
        
print(matriz)


Cuántas empresas?3
Cuántos empleados?4
[[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]
Ingrese el valor para la empresa 0, empleado045
Ingrese el valor para la empresa 0, empleado189
Ingrese el valor para la empresa 0, empleado252
Ingrese el valor para la empresa 0, empleado329
Ingrese el valor para la empresa 1, empleado032
Ingrese el valor para la empresa 1, empleado136
Ingrese el valor para la empresa 1, empleado257
Ingrese el valor para la empresa 1, empleado342
Ingrese el valor para la empresa 2, empleado045
Ingrese el valor para la empresa 2, empleado115
Ingrese el valor para la empresa 2, empleado248
Ingrese el valor para la empresa 2, empleado342
[[45, 89, 52, 29], [32, 36, 57, 42], [45, 15, 48, 42]]


•	Ejercicio [PromedioEmpleado] -> Codifique el siguiente programa:

- Modifique el anterior programa para que muestre el promedio de edades de los trabajadores de cada empresa.


In [13]:
f = int(input("Cuántas empresas?"))
c = int(input("Cuántos empleados por empresa?"))
matriz = [[0] * c for i in range(f)]
print(matriz)

for i in range(f):
    suma = 0
    for j in range(c):
        valor = int(input(f"Ingrese el valor para la empresa {i}, empleado{j}"))
        matriz[i][j] = valor
        suma = suma + matriz[i][j]
    promedio = suma / c
    print(f"El promedio de la empresa {i} es {promedio}")
    
print(matriz)


Cuántas empresas?3
Cuántos empleados por empresa?2
[[0, 0], [0, 0], [0, 0]]
Ingrese el valor para la empresa 0, empleado056
Ingrese el valor para la empresa 0, empleado196
El promedio de la empresa 0 es 76.0
Ingrese el valor para la empresa 1, empleado085
Ingrese el valor para la empresa 1, empleado195
El promedio de la empresa 1 es 90.0
Ingrese el valor para la empresa 2, empleado05
Ingrese el valor para la empresa 2, empleado15
El promedio de la empresa 2 es 5.0
[[56, 96], [85, 95], [5, 5]]


•	Ejercicio [PromedioEmpleado2] -> Codifique el siguiente programa:

- Debe crear una función llamada calcularPromedio(int[] edades); el cual recibe un arreglo de edades. Y retorna el promedio de las edades (double).

- Cree un for que recorre las empresas e invoque ese método desde el for cree construyo, y verifique que el programa funciona igual que el ejercicio 1.

In [15]:
def calcularPromedio(empresas):
    suma = 0
    for i in empresas:
        suma = suma + i
    return suma/len(empresas)

f = int(input("Cuántas empresas?"))
c = int(input("Cuántos empleados?"))
matriz = [[0] * c for i in range(f)]
print(matriz)

for i in range(f):
    for j in range(c):
        valor = int(input(f"Ingrese el valor para la empresa {i}, empleado{j}"))
        matriz[i][j] = valor
        
# For que recorra filas y mande cada fila a la función calcular promedio, se imprime el resultado
for i in range(f):
    print("Empresa", i)
    x = calcularPromedio(matriz[i])
    print("Edad promedio", x)
        
print(matriz)

Cuántas empresas?3
Cuántos empleados?2
[[0, 0], [0, 0], [0, 0]]
Ingrese el valor para la empresa 0, empleado05
Ingrese el valor para la empresa 0, empleado154
Ingrese el valor para la empresa 1, empleado052
Ingrese el valor para la empresa 1, empleado152
Ingrese el valor para la empresa 2, empleado054
Ingrese el valor para la empresa 2, empleado121
Empresa 0
Edad promedio 29.5
Empresa 1
Edad promedio 52.0
Empresa 2
Edad promedio 37.5
[[5, 54], [52, 52], [54, 21]]


# Operaciones con matrices
Usar la clase matriz o usar la libreria numpy.

- Para utilizar numpy debe intalar la librería:
    - Abrir la consola (Command prompt) como administrador 
    - Escribir el comando: `pip install numpy`
    - Enter y esperar a que se instale.

In [16]:
import numpy as np

edadesEmpresa2 = np.array([[34,25,16,32],[34,13,76,76]])
print(edadesEmpresa2)
print("Número de filas", len(edadesEmpresa2))
print("Número de columnas", len(edadesEmpresa2[0]))

[[34 25 16 32]
 [34 13 76 76]]
Número de filas 2
Número de columnas 4


In [19]:
import numpy as np
#Sumar todo
a = np.array([[3,12,55,1,3],[1,9,6,1,6],[4,1,2,2,5],[7,5,4,4,1]])
print(np.sum(a))

# Sumar filas
a = np.array([[3,12,55,1,3],[1,9,6,1,6],[4,1,2,2,5],[7,5,4,4,1]])
print(np.sum(a, axis = 1))

#Sumar columnas
a = np.array([[3,12,55,1,3],[1,9,6,1,6],[4,1,2,2,5],[7,5,4,4,1]])
print(np.sum(a, axis = 0)) 

132
[74 23 14 21]
[15 27 67  8 15]


In [20]:
# Transpuesta
a = np.array([[3,1,6,2,8],[9,7,7,2,1],[4,1,2,2,5],[7,5,4,4,1]])
print(a)

print(a.transpose())

[[3 1 6 2 8]
 [9 7 7 2 1]
 [4 1 2 2 5]
 [7 5 4 4 1]]
[[3 9 4 7]
 [1 7 1 5]
 [6 7 2 4]
 [2 2 2 4]
 [8 1 5 1]]


In [21]:

#Suma de dos matrices
a = np.array([[3,12,55,1,3],[1,9,6,1,6],[4,1,2,2,5],[7,5,4,4,1]])
b = np.array([[3,12,55,1,3],[1,9,6,1,6],[4,1,2,2,5],[7,5,4,4,1]])

print(np.add(a,b))

[[  6  24 110   2   6]
 [  2  18  12   2  12]
 [  8   2   4   4  10]
 [ 14  10   8   8   2]]


In [22]:
#Producto diagonal
a = np.array([[3,12,55,1,3],[1,9,6,1,6],[4,1,2,2,5],[7,5,4,4,1]])
print(a.diagonal())
print(a.diagonal().prod())

[3 9 2 4]
216


In [23]:
#Multiplicación de dos matrices
a = np.array([[3,12,55,1],[1,9,6,1],[4,1,2,2],[7,5,4,4]])
b = np.array([[3,12,55,1],[1,9,6,1],[4,1,2,2],[7,5,4,4]])

print(np.dot(a,b))

[[248 204 351 129]
 [ 43 104 125  26]
 [ 35  69 238  17]
 [ 70 153 439  36]]


In [25]:
a = np.array([[3,12,55,1],[1,9,6,1],[4,1,2,2],[7,5,4,4]])

#Matriz triangular superior
print(np.triu(a))
print(np.triu(a).sum())

#Matriz triangular extrictamente superior
print(np.triu(a,1))
print(np.triu(a).sum())


#Matriz triangular inferior
print(np.tril(a))
print(np.tril(a).sum())

#Matriz triangular extrictamente inferior
print(np.tril(a,-1))
print(np.tril(a,-1).sum())


[[ 3 12 55  1]
 [ 0  9  6  1]
 [ 0  0  2  2]
 [ 0  0  0  4]]
95
[[ 0 12 55  1]
 [ 0  0  6  1]
 [ 0  0  0  2]
 [ 0  0  0  0]]
95
[[3 0 0 0]
 [1 9 0 0]
 [4 1 2 0]
 [7 5 4 4]]
40
[[0 0 0 0]
 [1 0 0 0]
 [4 1 0 0]
 [7 5 4 0]]
22


# Ejercicios

•	Ejercicio [ArregloEmpleados] -> Codifique el siguiente programa:
- Cree un método de clase en la clase PrincipalEmpleado. 

- Ese método recibirá un arreglo de empleados, y retornará un valor double (el cual contiene el valor del mayor salario).

- Modifique el método main para imprimir ese mayor salario.

In [ ]:
class Empleado:
    def __init__(self, n, s):
        self.nombre = n
        self.salario = s